DROP DATABASE BIGBOWL;

CREATE DATABASE BIGBOWL;

\c bigbowl
CREATE TABLE DEPARTMENT (
    DEPT varchar(50) PRIMARY KEY
);

CREATE TABLE PANEL (
    LABEL varchar(100) NOT NULL,
    CTIME timestamp,
    IS_SEALED boolean DEFAULT FALSE,
    PANEL_ID bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE PANEL_REVIEW (
    PANEL_ID bigint GENERATED ALWAYS AS IDENTITY,
    REVIEW_NUMBER int NOT NULL,
    OPEN_TIME timestamp NOT NULL DEFAULT NOW(),
    CLOSE_TIME timestamp NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PANEL_ID, REVIEW_NUMBER),
    FOREIGN KEY (PANEL_ID) REFERENCES PANEL (PANEL_ID),
    CHECK (REVIEW_NUMBER > 0 AND REVIEW_NUMBER <= 5)
);

CREATE TABLE FACULTY (
    FAC_ID varchar(50) PRIMARY KEY,
    FIRST_NAME varchar(50) NOT NULL,
    LAST_NAME varchar(50) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    PHONE varchar(13) NOT NULL,
    DEPT varchar(50) NOT NULL,
    PANEL_ID bigint DEFAULT NULL,
    IS_COORDINATOR boolean DEFAULT FALSE,
    FOREIGN KEY (PANEL_ID) REFERENCES PANEL (PANEL_ID),
    FOREIGN KEY (DEPT) REFERENCES DEPARTMENT (DEPT),
    CHECK (EMAIL LIKE '%@%.%' AND PHONE LIKE '+__________')
);

CREATE TABLE TEAM (
    TEAM_NAME varchar(50) NOT NULL,
    DESCRIPTION varchar(200),
    GUIDE varchar(50) DEFAULT NULL,
    PANEL_ID bigint,
    TEAM_ID bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOREIGN KEY (PANEL_ID) REFERENCES PANEL (PANEL_ID),
    FOREIGN KEY (GUIDE) REFERENCES FACULTY (FAC_ID)
);

CREATE TABLE STUDENT (
    SRN varchar(15) PRIMARY KEY,
    FIRST_NAME varchar(50) NOT NULL,
    LAST_NAME varchar(50) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    PHONE varchar(13) NOT NULL,
    DEPT varchar(50) NOT NULL,
    TEAM_ID bigint,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID),
    CHECK (SRN LIKE 'PES%' AND EMAIL LIKE '%@%.%' AND PHONE LIKE '+__________'),
    FOREIGN KEY (DEPT) REFERENCES DEPARTMENT (DEPT)
);

CREATE TABLE TEAM_FACULTY (
    TEAM_ID bigint NOT NULL,
    FAC_ID varchar(50),
    REMARK_1 varchar(200) DEFAULT NULL,
    REMARK_2 varchar(200) DEFAULT NULL,
    REMARK_3 varchar(200) DEFAULT NULL,
    REMARK_4 varchar(200) DEFAULT NULL,
    REMARK_5 varchar(200) DEFAULT NULL,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID),
    FOREIGN KEY (FAC_ID) REFERENCES FACULTY (FAC_ID),
    PRIMARY KEY (TEAM_ID, FAC_ID)
);

CREATE TABLE EVALUATION_TABLE_INDIVIDUAL (
    SRN varchar(15) NOT NULL,
    TEAM_ID bigint NOT NULL,
    FAC_ID varchar(50),
    R1_PROJECT_WORK int NOT NULL,
    R1_QUALITY_OF_DEMO int NOT NULL,
    R1_PROJECT_REPORT int NOT NULL,
    R1_VIVA_VOCE int NOT NULL,
    R1_COMMENTS varchar(150) DEFAULT NULL,
    R2_PROJECT_WORK int NOT NULL,
    R2_QUALITY_OF_DEMO int NOT NULL,
    R2_PROJECT_REPORT int NOT NULL,
    R2_VIVA_VOCE int NOT NULL,
    R2_COMMENTS varchar(150) DEFAULT NULL,
    R3_PROJECT_WORK int NOT NULL,
    R3_QUALITY_OF_DEMO int NOT NULL,
    R3_PROJECT_REPORT int NOT NULL,
    R3_VIVA_VOCE int NOT NULL,
    R3_COMMENTS varchar(150) DEFAULT NULL,
    R4_PROJECT_WORK int NOT NULL,
    R4_QUALITY_OF_DEMO int NOT NULL,
    R4_PROJECT_REPORT int NOT NULL,
    R4_VIVA_VOCE int NOT NULL,
    R4_COMMENTS varchar(150) DEFAULT NULL,
    R5_PROJECT_WORK int NOT NULL,
    R5_QUALITY_OF_DEMO int NOT NULL,
    R5_PROJECT_REPORT int NOT NULL,
    R5_VIVA_VOCE int NOT NULL,
    R5_COMMENTS varchar(150) DEFAULT NULL,
    PRIMARY KEY (SRN, FAC_ID),
    FOREIGN KEY (SRN) REFERENCES STUDENT (SRN),
    FOREIGN KEY (TEAM_ID, FAC_ID) REFERENCES TEAM_FACULTY (TEAM_ID, FAC_ID),
    CHECK (R1_PROJECT_WORK <= 15 AND R1_PROJECT_WORK >= 0 AND R1_QUALITY_OF_DEMO <= 10 AND R1_QUALITY_OF_DEMO >= 0 AND R1_PROJECT_REPORT <= 10 AND R1_PROJECT_REPORT >= 0 AND R1_VIVA_VOCE <= 5 AND R1_VIVA_VOCE >= 0),
    CHECK (R2_PROJECT_WORK <= 15 AND R2_PROJECT_WORK >= 0 AND R2_QUALITY_OF_DEMO <= 10 AND R2_QUALITY_OF_DEMO >= 0 AND R2_PROJECT_REPORT <= 10 AND R2_PROJECT_REPORT >= 0 AND R2_VIVA_VOCE <= 5 AND R2_VIVA_VOCE >= 0),
    CHECK (R3_PROJECT_WORK <= 15 AND R3_PROJECT_WORK >= 0 AND R3_QUALITY_OF_DEMO <= 10 AND R3_QUALITY_OF_DEMO >= 0 AND R3_PROJECT_REPORT <= 10 AND R3_PROJECT_REPORT >= 0 AND R3_VIVA_VOCE <= 5 AND R3_VIVA_VOCE >= 0),
    CHECK (R4_PROJECT_WORK <= 15 AND R4_PROJECT_WORK >= 0 AND R4_QUALITY_OF_DEMO <= 10 AND R4_QUALITY_OF_DEMO >= 0 AND R4_PROJECT_REPORT <= 10 AND R4_PROJECT_REPORT >= 0 AND R4_VIVA_VOCE <= 5 AND R4_VIVA_VOCE >= 0),
    CHECK (R5_PROJECT_WORK <= 15 AND R5_PROJECT_WORK >= 0 AND R5_QUALITY_OF_DEMO <= 10 AND R5_QUALITY_OF_DEMO >= 0 AND R5_PROJECT_REPORT <= 10 AND R5_PROJECT_REPORT >= 0 AND R5_VIVA_VOCE <= 5 AND R5_VIVA_VOCE >= 0)
);

