DROP DATABASE BIGBOWL;
CREATE DATABASE BIGBOWL;
\c bigbowl
CREATE TABLE STUDENT
(
    SRN VARCHAR(15) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(13) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    CHECK (SRN LIKE 'PES%' AND EMAIL LIKE '%@%.%' AND PHONE LIKE '+__________')
);

CREATE TABLE FACULTY
(
    ID VARCHAR(50) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(13) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    CHECK (EMAIL LIKE '%@%.%' AND PHONE LIKE '+__________')
);

CREATE TABLE SUBJECT
(
    CODE VARCHAR(9) PRIMARY KEY,
    NAME VARCHAR(50),
    CHECK (CODE LIKE 'UE%')
);

CREATE TABLE TEAM
(
    TEAM_NAME VARCHAR(50) NOT NULL,
    CODE VARCHAR(9) NOT NULL,
    DESCRIPTION VARCHAR(200),
    GUIDE VARCHAR(50) DEFAULT NULL,
    TEAM_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOREIGN KEY(GUIDE) REFERENCES FACULTY(ID),
    FOREIGN KEY(CODE) REFERENCES SUBJECT(CODE),
    UNIQUE(TEAM_NAME,CODE)
);

CREATE TABLE STUDENT_SUBJECT
(
    SRN VARCHAR(15) NOT NULL,
    CODE VARCHAR(9) NOT NULL,
    BATCH VARCHAR(3) NOT NULL,
    PKEY_SS BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEAM_ID BIGINT DEFAULT NULL,
    FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID),
    FOREIGN KEY(SRN) REFERENCES STUDENT(SRN),
    FOREIGN KEY(CODE) REFERENCES SUBJECT(CODE)
);

CREATE TABLE FACULTY_SUBJECT
(
    ID VARCHAR(50) NOT NULL,
    CODE VARCHAR(9) NOT NULL,
    IS_ANCHOR BOOLEAN NOT NULL DEFAULT FALSE,
    PKEY_FS BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOREIGN KEY(ID) REFERENCES FACULTY(ID),
    FOREIGN KEY(CODE) REFERENCES SUBJECT(CODE)
);

CREATE TABLE PANEL
(
    LABEL VARCHAR(50) NOT NULL,
    REVIEW_NUMBER INT NOT NULL,
    TIME_STAMP DATE NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    PANEL_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CHECK (REVIEW_NUMBER >0 AND REVIEW_NUMBER<=6 )    
);

CREATE TABLE FACULTY_PANEL
(
    PKEY_FS BIGINT NOT NULL,
    PANEL_ID BIGINT NOT NULL,
    PKEY_FP BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOREIGN KEY(PKEY_FS) REFERENCES FACULTY_SUBJECT(PKEY_FS),
    FOREIGN KEY(PANEL_ID) REFERENCES PANEL(PANEL_ID)
);

CREATE TABLE TEAM_PANEL
(
    TEAM_ID BIGINT NOT NULL,
    PANEL_ID BIGINT NOT NULL,
    REMARKS VARCHAR(200) DEFAULT NULL,
    PKEY_FP BIGINT DEFAULT NULL,
    PKEY_TP BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOREIGN KEY(PANEL_ID) REFERENCES PANEL(PANEL_ID),
    FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID),
    FOREIGN KEY(PKEY_FP) REFERENCES FACULTY_PANEL(PKEY_FP)
);

CREATE TABLE EVALUATION_TABLE_INDIVIDUAL
(
    PKEY_SS BIGINT NOT NULL,
    PANEL_ID BIGINT NOT NULL,
    PROJECT_WORK INT NOT NULL,
    QUALITY_OF_DEMO INT NOT NULL,
    PROJECT_REPORT INT NOT NULL,
    VIVA_VOCE INT NOT NULL,
    COMMENTS VARCHAR(150) DEFAULT NULL,
    PRIMARY KEY(PKEY_SS,PANEL_ID),
    FOREIGN KEY(PANEL_ID) REFERENCES PANEL(PANEL_ID),
    FOREIGN KEY(PKEY_SS) REFERENCES STUDENT_SUBJECT(PKEY_SS),
    CHECK(PROJECT_WORK <=15 AND PROJECT_WORK >=0
    AND QUALITY_OF_DEMO <=10 AND QUALITY_OF_DEMO >=0
    AND PROJECT_REPORT <=10 AND PROJECT_REPORT >=0
    AND VIVA_VOCE <=5 AND VIVA_VOCE >=0)
);