DROP DATABASE BIGBOWL;
CREATE DATABASE BIGBOWL;
\c bigbowl
CREATE TABLE STUDENT
(
    SRN VARCHAR(15) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(13) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    CHECK (SRN LIKE 'PES%' AND EMAIL LIKE '%@%.%' AND PHONE LIKE '+__________')
);

CREATE TABLE FACULTY
(
    FAC_ID VARCHAR(50) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(13) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    IS_ANCHOR BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (EMAIL LIKE '%@%.%' AND PHONE LIKE '+__________')
);

CREATE TABLE SUBJECT
(
    CODE VARCHAR(9) PRIMARY KEY,
    NAME VARCHAR(50),
    CHECK (CODE LIKE 'UE%')
);

CREATE TABLE TEAM
(
    TEAM_NAME VARCHAR(50) NOT NULL,
    CODE VARCHAR(9) NOT NULL,
    DESCRIPTION VARCHAR(200),
    GUIDE VARCHAR(50) DEFAULT NULL,
    TEAM_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOREIGN KEY(GUIDE) REFERENCES FACULTY(FAC_ID),
    FOREIGN KEY(CODE) REFERENCES SUBJECT(CODE),
    UNIQUE (TEAM_NAME,CODE)
);

CREATE TABLE STUDENT_TEAM
(
    SRN VARCHAR(15),--not a primary key 
    TEAM_ID BIGINT,
    PKEY_ST BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOREIGN KEY(SRN) REFERENCES STUDENT(SRN),
    FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID),
    UNIQUE (TEAM_ID,SRN)
);

CREATE TABLE PANEL
(
    LABEL VARCHAR(50) NOT NULL,
    TIME_STAMP DATE NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    PANEL_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY--removed some old check constraint
);

CREATE TABLE FACULTY_PANEL
(
    FAC_ID VARCHAR(50),
    PANEL_ID BIGINT NOT NULL,
    PKEY_FP BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,--is it necessary?
    IS_COORDINATOR BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY(FAC_ID) REFERENCES FACULTY(FAC_ID),
    FOREIGN KEY(PANEL_ID) REFERENCES PANEL(PANEL_ID),
    UNIQUE (FAC_ID,PANEL_ID)
);

CREATE TABLE TEAM_PANEL
(
    TEAM_ID BIGINT NOT NULL,
    PANEL_ID BIGINT NOT NULL,
    REMARKS VARCHAR(200) DEFAULT NULL,
    PKEY_FP BIGINT DEFAULT NULL,
    PKEY_TP BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOREIGN KEY(PANEL_ID) REFERENCES PANEL(PANEL_ID),
    FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID),
    FOREIGN KEY(PKEY_FP) REFERENCES FACULTY_PANEL(PKEY_FP)--is not needed
);

CREATE TABLE EVALUATION_TABLE_INDIVIDUAL
(
    SRN VARCHAR(15) NOT NULL,
    PANEL_ID BIGINT NOT NULL,
    PROJECT_WORK INT NOT NULL,
    QUALITY_OF_DEMO INT NOT NULL,
    PROJECT_REPORT INT NOT NULL,
    VIVA_VOCE INT NOT NULL,
    EXAMINER VARCHAR(50),
    COMMENTS VARCHAR(150) DEFAULT NULL,--guess more will need to be added, tbd after 3:30
    PRIMARY KEY(SRN,PANEL_ID),
    FOREIGN KEY(PANEL_ID,EXAMINER) REFERENCES FACULTY_PANEL(PANEL_ID,FAC_ID),
    FOREIGN KEY(SRN) REFERENCES STUDENT(SRN),
    CHECK(PROJECT_WORK <=15 AND PROJECT_WORK >=0
    AND QUALITY_OF_DEMO <=10 AND QUALITY_OF_DEMO >=0
    AND PROJECT_REPORT <=10 AND PROJECT_REPORT >=0
    AND VIVA_VOCE <=5 AND VIVA_VOCE >=0)
);
